[build]
  command = "npm run build"
  publish = ".svelte-kit/output"

[functions]
  directory = ".netlify/functions"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200